In [1]:
import numpy as np

In [3]:
X = np.array([0,1,3])

In [4]:
np.append(X,1)

array([0, 1, 3, 1])

In [5]:
X=np.ones((3,10))

In [6]:
X

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
np.hstack((X,np.ones((3,1))))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
w = np.ones((3, 1))*3

In [9]:
w.shape, X.shape

((3, 1), (3, 10))

In [11]:
p=np.random.permutation(len(X))

In [13]:
X[p]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])