In [1]:
import numpy as np

In [2]:
X = np.array([0,1,3])

In [7]:
np.append(X,1)

array([0, 1, 3, 1])

In [3]:
X=np.ones((3,10))

In [4]:
X

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [22]:
np.hstack((X,np.ones((3,1))))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
w = np.ones((3, 1))*3

In [24]:
w.shape, X.shape

((3, 1), (3, 10))

In [26]:
np.transpose(X)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])