In [1]:
import numpy as np

In [3]:
X = np.array([0,1,3])

In [4]:
np.append(X,1)

array([0, 1, 3, 1])

In [5]:
X=np.ones((3,10))

In [6]:
X

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
np.hstack((X,np.ones((3,1))))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
w = np.ones((3, 2))*3

In [15]:
w.shape, X.shape

((3, 2), (3, 10))

In [17]:
exp_z = np.exp(X.T @ w) 
exp_z

array([[8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758]])

In [28]:
normalize = np.sum(exp_z, axis=1)
1/normalize

array([6.1704902e-05, 6.1704902e-05, 6.1704902e-05, 6.1704902e-05,
       6.1704902e-05, 6.1704902e-05, 6.1704902e-05, 6.1704902e-05,
       6.1704902e-05, 6.1704902e-05])

In [26]:
y_hat = np.divide(exp_z,normalize)
y_hat

ValueError: operands could not be broadcast together with shapes (10,2) (10,) 

In [34]:
np.sum(X, axis=1)

array([10., 10., 10.])