In [1]:
import numpy as np

In [7]:
X = np.random.rand(3,2)

In [16]:
X = np.zeros((3,2))
a = np.zeros((3,2))
a[0][0]=1

In [17]:
a, X

(array([[1., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]))

In [28]:
def one_hot_encode(Y: np.ndarray, num_classes: int):
    """
    Args:
        Y: shape [Num examples, 1]
        num_classes: Number of classes to use for one-hot encoding
    Returns:
        Y: shape [Num examples, num classes]
    """
    # TODO implement this function (Task 3a)
    
    Y_encoded = np.zeros((len(Y), num_classes))
    for i in range(len(Y)):
        Y_encoded[i][Y[i]] = 1
    return Y_encoded

In [39]:
y_hat = np.random.rand(3,2)
targets = np.zeros((3,2))

In [45]:
targets[0][0],targets[1][0],targets[2][0]=1,1,1

In [40]:
y_hat

array([[0.5169184 , 0.37663921],
       [0.03497399, 0.82702893],
       [0.06318195, 0.85837104]])

In [41]:
y_hat_digit = np.argmax(y_hat, axis=1)

In [46]:
y_hat_digit

array([0, 1, 1])

In [47]:
y_hat_binary = one_hot_encode(y_hat_digit, targets.shape[1])

In [48]:
y_hat_binary

array([[1., 0.],
       [0., 1.],
       [0., 1.]])

In [49]:
targets

array([[1., 0.],
       [1., 0.],
       [1., 0.]])

In [55]:
y_hat_binary == targets

array([[ True,  True],
       [False, False],
       [False, False]])

In [53]:
accuracy = np.mean(np.sum(y_hat_binary == targets, axis=1) == 2)

In [54]:
accuracy

0.3333333333333333

In [7]:
np.hstack((X,np.ones((3,1))))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
w = np.ones((3, 2))*3

In [15]:
w.shape, X.shape

((3, 2), (3, 10))

In [17]:
exp_z = np.exp(X.T @ w) 
exp_z

array([[8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758],
       [8103.08392758, 8103.08392758]])

In [28]:
normalize = np.sum(exp_z, axis=1)
1/normalize

array([6.1704902e-05, 6.1704902e-05, 6.1704902e-05, 6.1704902e-05,
       6.1704902e-05, 6.1704902e-05, 6.1704902e-05, 6.1704902e-05,
       6.1704902e-05, 6.1704902e-05])

In [26]:
y_hat = np.divide(exp_z,normalize)
y_hat

ValueError: operands could not be broadcast together with shapes (10,2) (10,) 

In [34]:
np.sum(X, axis=1)

array([10., 10., 10.])

In [62]:
def forward(X: np.ndarray) -> np.ndarray:
        """
        Args:
            X: images of shape [batch size, 785]
        Returns:
            y: output of model with shape [batch size, num_outputs]
        """
        # TODO implement this function (Task 3a)
        
        exp_z = np.exp(X) 
        normalize = np.sum(exp_z, axis=1)
        y_hat = np.diag(1/normalize) @ exp_z
        
        return y_hat

In [59]:
X = np.random.rand(5,3)

In [60]:
X

array([[0.17761305, 0.76299923, 0.74053112],
       [0.73265845, 0.84567167, 0.91553021],
       [0.67943166, 0.54249709, 0.01819818],
       [0.25079347, 0.55273581, 0.64057224],
       [0.73327744, 0.95603577, 0.92347903]])

In [64]:
y = forward(X)

In [65]:
np.sum(y, axis=1)

array([1., 1., 1., 1., 1.])