In [1]:
import numpy as np

In [2]:
X = np.array([0,1,3])

In [7]:
np.append(X,1)

array([0, 1, 3, 1])

In [10]:
X=np.ones((3,10))

In [17]:
X

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [22]:
np.hstack((X,np.ones((3,1))))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])